# Generated by Django 2.2.14 on 2020-07-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200716_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='gfhgfhgfhfhg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
