# Generated by Django 2.2.14 on 2020-07-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_customtext_gfhgfhgfhfhg"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="bvvcbcbvc",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
