# Generated by Django 2.2.14 on 2020-07-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_customtext_bvvcbcbvc"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="gfhgfhgfhfhg",),
    ]
