# Generated by Django 2.2.14 on 2020-07-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_customtext_gfhgfhgfhfhg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='bvvcbcbvc',
        ),
    ]
