# Generated by Django 2.2.14 on 2020-07-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200716_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFHTFYKJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhgjhgjhkjhkj', models.BigIntegerField()),
            ],
        ),
    ]
